# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=0.1.0
group=dev.gimme.sharedlife
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Shared Life
mod_author=Gimmeh
mod_id=sharedlife
license=MIT License
credits=
description=Makes all players share one health/hunger bar.
minecraft_version_range=[1.20.1]
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Forge, see https://files.minecraftforge.net/net/minecraftforge/forge/ for new versions
forge_version=47.4.13
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
