name: Build & Test

on: [workflow_call, push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      - name: Build
        run: make build

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: build-artifact
          path: |
            fabric/build/libs/*.jar
            neoforge/build/libs/*.jar
          if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      - name: Run checks
        run: make check

      - name: Upload test log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v6
        with:
          name: test-log
          path: build/test.log
          if-no-files-found: ignore
